apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-container
        image: rashed271202/django-app-image:v1.0  # Ensure there are no spaces in the image name or tag
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "loginproject.settings"
        - name: SECRET_KEY
          value: "django-insecure-o%=r^b2)pp&x*=&-6ot_tiki6zul_z%p-e6^iam0c2ceb-oad_"
        - name: ALLOWED_HOSTS
          value: "0.0.0.0"
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-app
  ports:
  - protocol: TCP
    port: 80        # Port exposed outside the cluster
    targetPort: 8000  # Port where Django app is running
  type: LoadBalancer
