apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-app
  ports:
  - protocol: TCP
    port: 80        # Port exposed outside the cluster
    targetPort: 8000  # Port where Django app is running
  type: LoadBalancer  # Expose it externally (Cloud setup) or use NodePort for local cluster
